// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr8Zd-x_-RyLSIKyaPdJUoat-8pTKpRVY',
    appId: '1:316750560337:web:0fa887d7d16cf5f091cc70',
    messagingSenderId: '316750560337',
    projectId: 'maims-ghglobal',
    authDomain: 'maims-ghglobal.firebaseapp.com',
    storageBucket: 'maims-ghglobal.firebasestorage.app',
    measurementId: 'G-EJXZS91LM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAATDmoj2GgdVENl3dYvpDn8VlsFInCBW4',
    appId: '1:316750560337:android:3c1db750840565ed91cc70',
    messagingSenderId: '316750560337',
    projectId: 'maims-ghglobal',
    storageBucket: 'maims-ghglobal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWP8DzufCKBRSC4toSpBo5dcETlKOPm60',
    appId: '1:316750560337:ios:424fcc8391a70d3b91cc70',
    messagingSenderId: '316750560337',
    projectId: 'maims-ghglobal',
    storageBucket: 'maims-ghglobal.firebasestorage.app',
    iosBundleId: 'com.example.checklist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWP8DzufCKBRSC4toSpBo5dcETlKOPm60',
    appId: '1:316750560337:ios:424fcc8391a70d3b91cc70',
    messagingSenderId: '316750560337',
    projectId: 'maims-ghglobal',
    storageBucket: 'maims-ghglobal.firebasestorage.app',
    iosBundleId: 'com.example.checklist',
  );

}