// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-dlEmicuYRNZS8pvXTB_0fbC7S8wvw4c',
    appId: '1:867124481361:web:77ffb5b5166e3ff8e51770',
    messagingSenderId: '867124481361',
    projectId: 'checklist-a49023',
    authDomain: 'checklist-a49023.firebaseapp.com',
    storageBucket: 'checklist-a49023.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzgibk1yhaDlDObp01ojxZpqzidAnf76U',
    appId: '1:867124481361:android:0493976649333f7fe51770',
    messagingSenderId: '867124481361',
    projectId: 'checklist-a49023',
    storageBucket: 'checklist-a49023.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABtCU2WACc0AnTTVgUYvNLbMhQGv5Id7Q',
    appId: '1:867124481361:ios:962c8e596ab94a1be51770',
    messagingSenderId: '867124481361',
    projectId: 'checklist-a49023',
    storageBucket: 'checklist-a49023.firebasestorage.app',
    iosBundleId: 'com.example.checklist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABtCU2WACc0AnTTVgUYvNLbMhQGv5Id7Q',
    appId: '1:867124481361:ios:962c8e596ab94a1be51770',
    messagingSenderId: '867124481361',
    projectId: 'checklist-a49023',
    storageBucket: 'checklist-a49023.firebasestorage.app',
    iosBundleId: 'com.example.checklist',
  );
}
